name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # For a plain HTML/JS project, this copies your files into a dist folder.
      - name: Build the project
        run: |
          mkdir -p dist
          cp index.html dist/index.html
          cp index.css dist/index.css
          cp enhanced-geopolitical-sim.jsx dist/enhanced-geopolitical-sim.jsx
          cp index.js dist/index.js
          cp server.js dist/server.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


