name: Generate test.yml workflow

on:
  push:
    branches: ["main"]

jobs:
  generate-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test.yml file
        run: |
          mkdir -p .github/workflows
          cat <<EOF > .github/workflows/test.yml
name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run typecheck

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
EOF

      - name: Commit and push test.yml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/workflows/test.yml
          git commit -m "Auto-generate test.yml workflow"
          git push
